# Generated by Django 3.1.3 on 2020-11-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=100000)),
                ('result', models.CharField(blank=True, max_length=100000)),
            ],
        ),
        migrations.DeleteModel(
            name='DatasetRaw',
        ),
    ]
